---
# Form running gradle locally
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
        url:  jdbc:h2:file:./h2/org
server:
  port: 8099

